---
- block:
  - name: user-settings | Include vars
    shell: whoami
    register: user_settings__r_user
    become: false

  - set_fact:
      ansible_user: "{{ user_settings__r_user.stdout }}"
  when: ansible_user is undefined

- name: user-settings | Include vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      ignore: true

- name: user-settings | Install software
  package:
    name: "{{ user_settings__packages }}"
    state: present
  become_user: root
  become: true
  become_method: sudo

- block:
  - name: user-settings | Apply settings for root
    include_tasks: _user_settings.yml
  become_user: root
  become: true
  become_method: sudo

- block:
  - name: user-settings | Apply settings for user
    include_tasks: _user_settings.yml
  become: false
  when: ansible_user != 'root'
