---
- name: user-settings | Include vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      ignore: true

- name: user-settings | Install software
  package:
    name: "{{ user_settings__packages }}"
    state: present
  become_user: root
  become: true
  become_method: sudo

- block:
  - name: user-settings | Apply settings for root
    include_tasks: _user_settings.yml
  become_user: root
  become: true
  become_method: sudo

- block:
  - name: user-settings | Apply settings for user
    include_tasks: _user_settings.yml
  become: false
  when: ansible_user != 'root'
